#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def clamp01(v: float) -> float:
    if v < 0:
        return 0.0
    if v > 1:
        return 1.0
    return v


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Replay the current Pixelblaze detector logic against a captured Pixelblaze CSV log."
    )
    parser.add_argument("capture_csv", type=Path, help="CSV generated by capture_pixelblaze_vars.py")
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=None,
        help="Optional output prefix for replay CSV/JSON summary",
    )
    parser.add_argument(
        "--trim-active",
        action="store_true",
        help="Trim and realign to the detected active playback window using energy/spectral activity.",
    )
    parser.add_argument(
        "--active-start",
        type=float,
        default=None,
        help="Manual active-window start time in seconds. When set, subtract this from ts_rel.",
    )
    parser.add_argument(
        "--active-end",
        type=float,
        default=None,
        help="Manual active-window end time in seconds. When set, rows after this time are discarded.",
    )
    parser.add_argument(
        "--active-sum-threshold-frac",
        type=float,
        default=0.15,
        help="When --trim-active is used, require summed frequencyData above this fraction of its max.",
    )
    parser.add_argument(
        "--active-energy-threshold-frac",
        type=float,
        default=0.20,
        help="When --trim-active is used, require energyAverage above this fraction of its max.",
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open() as handle:
        return list(csv.DictReader(handle))


def detect_active_window(
    rows: list[dict[str, str]],
    sum_threshold_frac: float,
    energy_threshold_frac: float,
) -> tuple[float, float] | None:
    vals: list[tuple[float, float, float]] = []
    for row in rows:
        ts_rel = float(row["ts_rel"])
        energy = float(row.get("energyAverage", 0) or 0)
        band_sum = 0.0
        for i in range(32):
            band_sum += float(row.get(f"frequencyData_{i:02d}", 0) or 0)
        vals.append((ts_rel, energy, band_sum))

    if not vals:
        return None

    smoothed: list[tuple[float, float, float]] = []
    window = 5
    for i, (ts_rel, _, _) in enumerate(vals):
        chunk = vals[max(0, i - window + 1) : i + 1]
        mean_energy = sum(v[1] for v in chunk) / len(chunk)
        mean_sum = sum(v[2] for v in chunk) / len(chunk)
        smoothed.append((ts_rel, mean_energy, mean_sum))

    max_sum = max(v[2] for v in smoothed)
    max_energy = max(v[1] for v in smoothed)
    sum_threshold = max_sum * sum_threshold_frac
    energy_threshold = max_energy * energy_threshold_frac
    active_times = [
        ts_rel
        for ts_rel, energy, band_sum in smoothed
        if (band_sum >= sum_threshold) or (energy >= energy_threshold)
    ]
    if not active_times:
        return None
    return min(active_times), max(active_times)


def main() -> int:
    args = parse_args()
    rows = load_rows(args.capture_csv)
    if not rows:
        raise SystemExit("Capture CSV is empty")

    active_start = 0.0
    active_end = None
    if args.active_start is not None:
        active_start = args.active_start
    elif args.trim_active:
        active_window = detect_active_window(
            rows,
            sum_threshold_frac=args.active_sum_threshold_frac,
            energy_threshold_frac=args.active_energy_threshold_frac,
        )
        if active_window is None:
            raise SystemExit("Could not detect an active playback window")
        active_start, active_end = active_window

    if args.active_end is not None:
        active_end = args.active_end

    onsetLowThreshold = float(rows[0].get("dbgOnsetLowThreshold", 0.10))
    onsetThreshold = float(rows[0].get("dbgOnsetThreshold", 0.035))
    peakPickWindowMs = float(rows[0].get("dbgPeakPickWindowMs", 240))
    refractoryMs = float(rows[0].get("dbgRefractoryMs", 180))
    energyFloor = float(rows[0].get("dbgEnergyFloor", 0.0012))
    lowRawFloor = float(rows[0].get("dbgLowRawFloor", 0.0005))
    lowBodyRawFloor = float(rows[0].get("dbgLowBodyRawFloor", 0.0010))

    # Pixelblaze-calibrated grouping based on captured Monolink analysis.
    coreRawFloor = max(lowRawFloor, 0.060)
    supportRawFloor = max(lowBodyRawFloor, 0.160)
    ratioThreshold = 3.0
    rawRatioThreshold = 14.0
    contaminationNormMax = 0.68
    contaminationWeightedMax = 0.11

    pulseAgeMs = 99999.0
    flashStrength = 1.0
    corePeak = 0.0001
    bodyPeak = 0.0001
    contaminationPeak = 0.0001
    prevCoreNorm = 0.0
    pendingActive = 0
    pendingAgeMs = 0.0
    pendingBestScore = 0.0
    pendingBestStrength = 1.0
    refractoryLeftMs = 0.0

    replay_rows: list[dict[str, float | int]] = []

    prev_ts = None
    for row in rows:
        ts_rel_raw = float(row["ts_rel"])
        if ts_rel_raw < active_start:
            continue
        if active_end is not None and ts_rel_raw > active_end:
            continue

        ts_rel = ts_rel_raw - active_start
        delta = 0.0 if prev_ts is None else max(0.0, (ts_rel - prev_ts) * 1000.0)
        prev_ts = ts_rel

        pulseAgeMs += delta
        if refractoryLeftMs > 0:
            refractoryLeftMs -= delta
            if refractoryLeftMs < 0:
                refractoryLeftMs = 0

        bins = [float(row[f"frequencyData_{i:02d}"]) for i in range(32)]
        coreRaw = sum(bins[1:7]) / 6.0
        bodyRaw = sum(bins[7:12]) / 5.0
        contaminationRaw = sum(bins[21:26]) / 5.0
        energyAverage = float(row["energyAverage"])

        signalActive = int(
            (energyAverage > energyFloor)
            and ((coreRaw > coreRawFloor) or ((coreRaw + bodyRaw) > supportRawFloor))
        )

        peakDecay = pow(0.55, delta / 1000.0) if delta > 0 else 1.0
        corePeak *= peakDecay
        bodyPeak *= peakDecay
        contaminationPeak *= peakDecay

        if coreRaw > corePeak:
            corePeak = coreRaw
        if bodyRaw > bodyPeak:
            bodyPeak = bodyRaw
        if contaminationRaw > contaminationPeak:
            contaminationPeak = contaminationRaw

        if corePeak < 0.0001:
            corePeak = 0.0001
        if bodyPeak < 0.0001:
            bodyPeak = 0.0001
        if contaminationPeak < 0.0001:
            contaminationPeak = 0.0001

        lowNorm = clamp01(coreRaw / corePeak)
        bodyNorm = clamp01(bodyRaw / bodyPeak)
        highNorm = clamp01(contaminationRaw / contaminationPeak)
        lowRise = lowNorm - prevCoreNorm
        if lowRise < 0:
            lowRise = 0.0
        prevCoreNorm = lowNorm

        ratio = (lowNorm + bodyNorm + 0.0001) / (highNorm + 0.0001)
        rawRatio = (coreRaw + bodyRaw + 0.0001) / (contaminationRaw + 0.0001)
        highDominant = int(highNorm > contaminationNormMax)
        rawBassSupport = int((coreRaw + 0.85 * bodyRaw) > (contaminationRaw * rawRatioThreshold / 2.0))
        lowQualified = int((coreRaw > coreRawFloor) and ((coreRaw + bodyRaw) > supportRawFloor))
        contaminationWeighted = contaminationRaw / max(coreRaw + 0.6 * bodyRaw, 0.0001)

        candidate = int(
            signalActive
            and (lowNorm > onsetLowThreshold)
            and (ratio > ratioThreshold)
            and (rawRatio > rawRatioThreshold)
            and rawBassSupport
            and lowQualified
            and not highDominant
            and (contaminationWeighted < contaminationWeightedMax)
            and ((lowRise > onsetThreshold) or (lowNorm > 0.82))
        )

        if not signalActive:
            pendingActive = 0
            pendingAgeMs = 0.0
            pendingBestScore = 0.0
            pendingBestStrength = 1.0
            prevCoreNorm *= 0.5

        if candidate:
            ratioClamped = ratio
            if ratioClamped > 4:
                ratioClamped = 4
            riseScore = lowRise if lowRise > onsetThreshold else onsetThreshold
            score = riseScore * (lowNorm + 0.7 * bodyNorm) * ratioClamped
            strength = clamp01(0.50 + 0.35 * lowNorm + 0.15 * bodyNorm)
            if not pendingActive:
                pendingActive = 1
                pendingAgeMs = 0.0
                pendingBestScore = score
                pendingBestStrength = strength
            elif score > pendingBestScore:
                pendingBestScore = score
                pendingBestStrength = strength

        accepted = 0
        if pendingActive:
            pendingAgeMs += delta
            if pendingAgeMs >= peakPickWindowMs:
                if refractoryLeftMs <= 0:
                    pulseAgeMs = 0.0
                    flashStrength = pendingBestStrength
                    refractoryLeftMs = refractoryMs
                    accepted = 1
                pendingActive = 0
                pendingAgeMs = 0.0
                pendingBestScore = 0.0
                pendingBestStrength = 1.0

        replay_rows.append(
            {
                "ts_rel": ts_rel,
                "replay_lowNorm": lowNorm,
                "replay_bodyNorm": bodyNorm,
                "replay_highNorm": highNorm,
                "replay_lowRise": lowRise,
                "replay_ratio": ratio,
                "replay_rawRatio": rawRatio,
                "replay_coreRaw": coreRaw,
                "replay_bodyRaw": bodyRaw,
                "replay_contaminationRaw": contaminationRaw,
                "replay_contaminationWeighted": contaminationWeighted,
                "replay_signalActive": signalActive,
                "replay_highDominant": highDominant,
                "replay_lowQualified": lowQualified,
                "replay_rawBassSupport": rawBassSupport,
                "replay_candidate": candidate,
                "replay_pendingScore": pendingBestScore,
                "replay_accepted": accepted,
                "logged_candidate": int(float(row.get("dbgCandidate", 0))),
                "logged_accepted": int(float(row.get("dbgAccepted", 0))),
            }
        )

    if not replay_rows:
        raise SystemExit("No rows remain after applying active-window trimming")

    cand_match = sum(1 for r in replay_rows if r["replay_candidate"] == r["logged_candidate"])
    acc_match = sum(1 for r in replay_rows if r["replay_accepted"] == r["logged_accepted"])
    summary = {
        "rows": len(replay_rows),
        "active_start_s": active_start,
        "active_end_s": active_end,
        "candidate_match_rows": cand_match,
        "accepted_match_rows": acc_match,
        "candidate_match_ratio": cand_match / len(replay_rows),
        "accepted_match_ratio": acc_match / len(replay_rows),
        "replay_candidate_count": sum(int(r["replay_candidate"]) for r in replay_rows),
        "logged_candidate_count": sum(int(r["logged_candidate"]) for r in replay_rows),
        "replay_accepted_count": sum(int(r["replay_accepted"]) for r in replay_rows),
        "logged_accepted_count": sum(int(r["logged_accepted"]) for r in replay_rows),
    }

    print(json.dumps(summary, indent=2))

    if args.output_prefix is not None:
        csv_path = args.output_prefix.with_suffix(".csv")
        json_path = args.output_prefix.with_suffix(".json")
        csv_path.parent.mkdir(parents=True, exist_ok=True)
        with csv_path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(replay_rows[0].keys()))
            writer.writeheader()
            writer.writerows(replay_rows)
        with json_path.open("w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2)
        print(f"Wrote replay rows to {csv_path}")
        print(f"Wrote replay summary to {json_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
